import { i18n } from "../i18n";

type ErrorPattern = [RegExp, (match: RegExpMatchArray) => string];

const exactPairs = [
  ["请求失败", "Request failed"],
  ["上传失败", "Upload failed"],
  ["上传失败，请检查网络连接", "Upload failed. Please check your network connection."],
  ["请先登录", "Please log in first"],
  ["仅管理员可执行此操作", "Only administrators can perform this action"],

  ["平台账号登录未启用", "Platform account login is disabled"],
  ["用户名或密码错误", "Incorrect username or password"],
  ["用户名格式不合法", "Invalid username format"],
  ["邮箱格式不合法", "Invalid email format"],
  ["联系邮箱格式不合法", "Invalid email format"],
  ["密码至少需要 10 个字符", "Password must be at least 10 characters"],
  ["新密码至少需要 10 个字符", "New password must be at least 10 characters"],
  ["当前密码错误", "Current password is incorrect"],
  ["平台注册未启用", "Platform registration is disabled"],
  ["用户名已存在", "Username already exists"],
  ["邮箱已被注册", "Email is already registered"],
  ["默认注册分组不存在", "Default registration group does not exist"],

  ["用户不存在", "User does not exist"],
  ["用户名称不能为空", "Display name is required"],
  ["用户分组不合法", "Invalid user group"],
  ["配额不能为负数", "Quota values cannot be negative"],
  ["配额分组不存在", "Quota group does not exist"],
  ["不能禁用自己或移除自己的管理员角色", "You cannot disable yourself or remove your own administrator role"],
  ["不能移除自己", "You cannot remove yourself"],
  ["新用户初始密码至少需要 10 个字符", "Initial password must be at least 10 characters"],
  ["SSH 公钥不能为空", "SSH public key is required"],
  ["SSH 公钥格式不合法", "Invalid SSH public key format"],
  ["SSH 公钥不存在", "SSH public key does not exist"],
  ["没有有效的 SSH 公钥可以同步", "No valid SSH public keys can be synced"],
  ["没有可同步的容器", "No containers can be synced"],
  ["无效的 casdoor_id 格式", "Invalid casdoor_id format"],
  ["该 Casdoor 用户已关联平台账号", "This Casdoor user is already linked to a platform account"],

  ["节点不存在", "Node does not exist"],
  ["节点地址缺失", "Node address is missing"],
  ["hostname 不合法", "Invalid hostname"],
  ["预期 hostname 不合法", "Invalid expected hostname"],
  ["有效期必须在 1-720 小时之间", "Validity must be between 1 and 720 hours"],
  ["节点 token 与已注册节点不匹配", "Node token does not match the registered node"],
  ["节点注册 token 无效、已使用或已过期", "Node registration token is invalid, used, or expired"],
  ["节点注册 token 与 hostname 不匹配", "Node registration token does not match the hostname"],
  ["该节点仍有关联容器，请先删除或迁移容器", "This node still has containers. Delete or migrate them first."],
  ["请先配置节点 WOL MAC 地址", "Please configure the node WOL MAC address first"],
  ["WOL MAC 地址格式不合法", "Invalid WOL MAC address format"],
  ["WOL 广播地址不合法", "Invalid WOL broadcast address"],
  ["SSH 用户名格式不合法", "Invalid SSH username format"],
  ["SSH 端口必须在 1-65535 之间", "SSH port must be between 1 and 65535"],
  ["同步 SSH 端口必须在 0-65535 之间", "Sync SSH port must be between 0 and 65535"],
  ["scheduler_weight 必须在 -1000 到 1000 之间", "scheduler_weight must be between -1000 and 1000"],
  ["节点标签最多 20 个", "At most 20 node labels are allowed"],

  ["容器不存在", "Container does not exist"],
  ["只能操作自己的容器", "You can only operate your own containers"],
  ["容器名称必须以小写字母开头，只包含小写字母、数字和连字符", "Container name must start with a lowercase letter and contain only lowercase letters, digits, and hyphens"],
  ["初始用户名不合法", "Invalid initial username"],
  ["请填写 SSH 公钥，平台已禁用容器 SSH 密码登录", "Please enter an SSH public key. SSH password login is disabled by the platform."],
  ["镜像不存在", "Image does not exist"],
  ["容器镜像不存在", "Container image does not exist"],
  ["容器所在节点不存在", "The container's node does not exist"],
  ["只有 failed 状态的容器可以重试创建", "Only failed containers can retry creation"],
  ["只有 running 状态的容器可以重试 SSH 准备", "Only running containers can retry SSH preparation"],
  ["容器缺少 SSH 公钥，无法准备 SSH", "The container has no SSH public key, so SSH cannot be prepared"],
  ["只有 running 或 stopped 状态的容器可以修改配置", "Only running or stopped containers can be reconfigured"],
  ["CPU 核数不能小于 1", "CPU cores cannot be less than 1"],
  ["内存不能小于 1 GB", "Memory cannot be less than 1 GB"],
  ["超出用户 CPU 配额", "User CPU quota exceeded"],
  ["超出用户内存配额", "User memory quota exceeded"],
  ["超出用户 GPU 配额", "User GPU quota exceeded"],
  ["命令不能为空", "Command is required"],
  ["命令过长", "Command is too long"],
  ["只有 running 容器可以打开 shell", "Only running containers can open a shell"],
  ["镜像别名格式不合法", "Invalid image alias format"],
  ["容器必须是 running 或 stopped 状态才能同步", "Container must be running or stopped before syncing"],
  ["同步规则不存在", "Sync rule does not exist"],
  ["同步方向不合法", "Invalid sync direction"],
  ["该节点不允许端口映射", "This node does not allow port mapping"],
  ["端口映射不存在", "Port mapping does not exist"],
  ["该容器内端口映射已存在", "This container port mapping already exists"],
  ["端口协议只支持 tcp 或 udp", "Port protocol only supports tcp or udp"],
  ["容器内端口必须在 1-65535 之间", "Container port must be between 1 and 65535"],
  ["仅管理员可强制移除容器记录", "Only administrators can force-remove container records"],
  ["容器名称确认不匹配", "Container name confirmation does not match"],

  ["镜像 ID 只能包含字母、数字、点、下划线、冒号和连字符", "Image ID can only contain letters, digits, dots, underscores, colons, and hyphens"],
  ["镜像名称不能为空", "Image name is required"],
  ["Incus 镜像引用不能为空", "Incus image reference is required"],
  ["incus_ref 不能为空", "incus_ref is required"],
  ["CUDA 主版本不合法", "Invalid CUDA major version"],
  ["目标节点不在线或不是计算节点", "Target node is offline or is not a compute node"],
  ["当前没有在线的计算节点", "There are no online compute nodes"],
  ["自建镜像不存在", "Custom image does not exist"],
  ["仓库镜像不存在", "Repository image does not exist"],
  ["镜像尚未导出成功，不能分发", "The image has not been exported successfully and cannot be distributed"],

  ["用户目录所在存储节点不在线", "The storage node for the user directory is offline"],
  ["用户目录策略不存在，请先打开存储中心初始化我的文件", "User directory policy does not exist. Open Storage Center first to initialize My Files."],
  ["用户或用户目录策略不存在", "User or user directory policy does not exist"],
  ["没有 online 的 storage/mixed 节点可访问我的文件", "No online storage/mixed node can access My Files"],
  ["没有 online 的 storage/mixed 节点可访问公开资源", "No online storage/mixed node can access public resources"],
  ["公开数据集/模型不存在", "Public dataset/model does not exist"],
  ["存储节点地址缺失", "Storage node address is missing"],
  ["目录相对路径不合法", "Invalid directory relative path"],
  ["目录相对路径过长", "Directory relative path is too long"],
  ["上传文件名不能为空", "Upload filename is required"],
  ["上传路径过长", "Upload path is too long"],
  ["上传路径不合法", "Invalid upload path"],
  ["上传路径片段过长", "Upload path segment is too long"],
  ["上传路径越界", "Upload path escapes the allowed directory"],
  ["存储路径不合法", "Invalid storage path"],
  ["存储根目录不合法", "Invalid storage root"],
  ["上传文件与路径数量不一致", "The number of files and paths does not match"],
  ["请选择要上传的文件", "Please choose files to upload"],
  ["文件大小不可用", "File size is unavailable"],
  ["下载目标不存在", "Download target does not exist"],
  ["只能预览具体文件", "Only files can be previewed"],
  ["不能删除用户根目录", "Cannot delete the user root directory"],
  ["删除路径越界", "Delete path escapes the allowed directory"],
  ["文件或目录不存在", "File or directory does not exist"],
  ["共享资源不存在", "Shared resource does not exist"],
  ["共享资源名称不合法", "Invalid shared resource name"],
  ["资源名称不合法", "Invalid resource name"],
  ["资源版本不合法", "Invalid resource version"],
  ["资源提供者不合法", "Invalid resource provider"],
  ["标签不合法", "Invalid tag"],
  ["标签最多 20 个", "At most 20 tags are allowed"],
  ["没有在线存储节点", "There is no online storage node"],
  ["没有 online 的 storage/mixed 节点可执行校验", "No online storage/mixed node can verify resources"],
  ["没有 online 的 storage/mixed 节点可扫描资源目录", "No online storage/mixed node can scan the resource directory"],
  ["资源所在存储节点不在线", "The storage node for this resource is offline"],
  ["source 不合法，应为 huggingface 或 modelscope", "Invalid source. Expected huggingface or modelscope."],
  ["ModelScope 仓库 ID 不合法，格式应为 owner/repo-name", "Invalid ModelScope repository ID. Expected owner/repo-name."],
  ["HuggingFace 仓库 ID 不合法，格式应为 owner/repo-name", "Invalid HuggingFace repository ID. Expected owner/repo-name."],
  ["HF 镜像站地址不合法", "Invalid HF mirror URL"],

  ["ZFS dataset 任务未配置", "ZFS dataset task is not configured"],
  ["ZFS dataset 移除任务未配置", "ZFS dataset removal task is not configured"],
  ["只能移除未启用用户的 ZFS dataset", "Only disabled users' ZFS datasets can be removed"],
  ["用户节点数据卷回收任务未配置", "User node volume reclaim task is not configured"],
  ["用户节点数据卷不存在", "User node volume does not exist"],
  ["请输入数据卷名确认回收", "Please enter the volume name to confirm reclaim"],
  ["该用户在当前节点仍有容器，不能回收数据卷", "This user still has containers on the current node, so the volume cannot be reclaimed"],
  ["数据卷所在节点不在线", "The volume's node is offline"],

  ["SSO Provider 不存在", "SSO provider does not exist"],
  ["SSO 回调基础地址未配置", "SSO callback base URL is not configured"],
  ["无效或已过期的认证状态，请重新发起登录", "Invalid or expired authentication state. Please start login again."],
  ["对应的 SSO Provider 已不存在", "The corresponding SSO provider no longer exists"],
  ["账号不存在，请联系管理员手动创建账号后再使用统一认证登录", "Account does not exist. Contact an administrator to create it before using SSO login."],
  ["账号待审核，请等待管理员在平台用户管理中启用您的账号", "Account is pending review. Wait for an administrator to enable it in User Management."],

  ["SSO Provider 标识只能包含小写字母、数字、下划线和中划线", "SSO provider ID can only contain lowercase letters, digits, underscores, and hyphens"],
  ["平台时区不合法，请使用 IANA 时区名，例如 Asia/Shanghai", "Invalid platform timezone. Use an IANA timezone such as Asia/Shanghai."],
  ["传输带宽上限必须在 0-100000 Mbps 之间", "Transfer bandwidth limit must be between 0 and 100000 Mbps"],
  ["启用 SSO 时必须填写回调基础地址", "Callback base URL is required when SSO is enabled"],
  ["启用 CAS 时必须填写 CAS 服务地址", "CAS server URL is required when CAS is enabled"],
  ["启用 OIDC 时必须填写 Client ID 和 Client Secret", "Client ID and Client Secret are required when OIDC is enabled"],
  ["启用 OIDC 时必须填写 Issuer，或完整填写授权/令牌/用户信息端点", "Issuer is required when OIDC is enabled, or fill all authorization/token/userinfo endpoints."],
] as const;

const exactEn = new Map<string, string>();
for (const [source, target] of exactPairs) {
  exactEn.set(source, target);
  exactEn.set(compactKey(source), target);
}

const patterns: ErrorPattern[] = [
  [/^(.+) 必须是绝对路径$/, (m) => `${m[1]} must be an absolute path`],
  [/^(.+) 不合法$/, (m) => `Invalid ${m[1]}`],
  [/^(.+) 过长$/, (m) => `${m[1]} is too long`],
  [/^(.+) 不能为负数$/, (m) => `${m[1]} cannot be negative`],
  [/^节点标签不合法：(.+)$/, (m) => `Invalid node label: ${m[1]}`],
  [/^节点不存在：(.+)$/, (m) => `Node does not exist: ${m[1]}`],
  [/^超出用户额度：(.+)$/, (m) => `User quota exceeded: ${m[1]}`],
  [/^超出节点单容器 CPU 上限：(.+) 核$/, (m) => `Exceeds node per-container CPU limit: ${m[1]} cores`],
  [/^超出节点单容器内存上限：(.+) GB$/, (m) => `Exceeds node per-container memory limit: ${m[1]} GB`],
  [/^节点上没有足够的可用 GPU（需要 (.+) 张额外 GPU）$/, (m) => `Not enough available GPUs on the node (${m[1]} additional GPUs required)`],
  [/^容器正在 (.+)，请稍后再试$/, (m) => `Container is ${m[1]}. Please try again later.`],
  [/^容器正在 (.+)，请使用强制移除记录$/, (m) => `Container is ${m[1]}. Use force-remove record.`],
  [/^该节点单容器最多允许 (.+) 个端口映射$/, (m) => `This node allows at most ${m[1]} port mappings per container`],
  [/^(.+)端口范围配置不合法$/, (m) => `Invalid ${m[1]} port range configuration`],
  [/^(.+)端口池已用尽$/, (m) => `${m[1]} port pool is exhausted`],
  [/^标签过长：(.+)$/, (m) => `Tag is too long: ${m[1]}`],
  [/^上传总大小超过限制（(.+) MB）$/, (m) => `Total upload size exceeds the limit (${m[1]} MB)`],
  [/^用户目录超过存储上限（(.+) GB）$/, (m) => `User directory exceeds the storage quota (${m[1]} GB)`],
  [/^目标已存在同名目录：(.+)$/, (m) => `A directory with the same name already exists at the target: ${m[1]}`],
  [/^无法获取远程镜像列表: (.+)$/, (m) => `Failed to fetch remote image list: ${m[1]}`],
  [/^SSO 认证失败：(.+)$/, (m) => `SSO authentication failed: ${m[1]}`],
  [/^存储节点临时同步密钥安装失败: (.+)$/, (m) => `Failed to install temporary sync key on storage node: ${m[1]}`],
  [/^上传到存储节点失败：(.+)$/, (m) => `Failed to upload to storage node: ${m[1]}`],
  [/^无法连接存储节点执行下载：(.+)$/, (m) => `Cannot connect to storage node to download: ${m[1]}`],
  [/^无法连接存储节点执行删除：(.+)$/, (m) => `Cannot connect to storage node to delete: ${m[1]}`],
  [/^文件预览失败：(.+)$/, (m) => `File preview failed: ${m[1]}`],
  [/^删除失败：(.+)$/, (m) => `Delete failed: ${m[1]}`],
  [/^ls 执行失败: (.+)$/, (m) => `ls execution failed: ${m[1]}`],
  [/^SSH 连接存储节点失败: (.+)$/, (m) => `SSH connection to storage node failed: ${m[1]}`],
  [/^无法连接 Docker socket，请确认 \/var\/run\/docker\.sock 已挂载并授权：(.+)$/, (m) => `Cannot connect to Docker socket. Make sure /var/run/docker.sock is mounted and authorized: ${m[1]}`],
  [/^编译失败：\n?(.+)$/s, (m) => `Build failed:\n${m[1]}`],
  [/^Docker API 错误：(.+)$/, (m) => `Docker API error: ${m[1]}`],
];

function compactKey(message: string) {
  return message.replace(/\s+/g, "").replace(/[/:（），。]/g, "_");
}

export function translateApiError(message: unknown) {
  const text = typeof message === "string" && message.trim() ? message.trim() : "请求失败";
  if (i18n.global.locale.value !== "en-US") return text;
  const exact = exactEn.get(text) || exactEn.get(compactKey(text));
  if (exact) return exact;
  for (const [pattern, format] of patterns) {
    const match = text.match(pattern);
    if (match) return format(match);
  }
  return text;
}
